# karmasoc-mediaserve
FROM node:4

# Create app directory
RUN mkdir -p /usr/src/app/karmasoc-mediaserve
RUN mkdir -p /usr/src/app/karmasoc-mediaserve/config

COPY ./process.json /usr/src/app/karmasoc-mediaserve
COPY ./config /usr/src/app/karmasoc-mediaserve/config
COPY ./karmasoc-mediaserve /usr/src/app/karmasoc-mediaserve

WORKDIR /usr/src/app/karmasoc-mediaserve

RUN npm install pm2 -g
RUN npm install --unsafe-perm=true
RUN npm run build

EXPOSE 44001

CMD pm2 start --no-daemon  process.json --only karmasoc-mediaserve --env docker
