# karmasoc-user
FROM node:4

# Create app directory
RUN mkdir -p /usr/src/app/karmasoc-posts
RUN mkdir -p /usr/src/app/karmasoc-posts/config

COPY ./process.json /usr/src/app/karmasoc-posts
COPY ./config /usr/src/app/karmasoc-posts/config
COPY ./karmasoc-user /usr/src/app/karmasoc-posts

WORKDIR /usr/src/app/karmasoc-posts

RUN npm install pm2 -g
RUN npm install --unsafe-perm=true
RUN npm run build

EXPOSE 44001

CMD pm2 start --no-daemon  process.json --only karmasoc-posts --env docker
